services:
  - type: web
    name: telegram-bot
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        scope: run
      - key: DATABASE_URL
        scope: run
